# Generated by Django 3.2.12 on 2023-11-02 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizes'},
        ),
    ]
